/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {

  protected String classId, extendsId;

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Parser p, int id) {
    super(p, id);
  }

  /**
   * @return the classId
   */
  public String getClassId() {
    return classId;
  }

  /**
   * @return the extendsId
   */
  public String getExtendsId() {
    return extendsId;
  }

  @Override
  public String toString() {
    return super.toString() + " [ name=\'" + classId + "\' ]";
  }

}
/* JavaCC - OriginalChecksum=f51417f6449106e8d43b74bfe2badc1b (do not edit this line) */
