/* Generated By:JJTree: Do not edit this line. ASTDot.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDot extends SimpleNode {
  public ASTDot(int id) {
    super(id);
  }

  public ASTDot(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73adb5ff2e76889e0d73bb59fcf8a766 (do not edit this line) */
