/* Generated By:JJTree: Do not edit this line. ASTDividor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDividor extends SimpleNode {
  public ASTDividor(int id) {
    super(id);
  }

  public ASTDividor(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d9f0450d9ed8db3ff2404f46d1535085 (do not edit this line) */
