/* Generated By:JJTree: Do not edit this line. ASTEqualsId.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEqualsId extends SimpleNode {

  protected String identifier;

  public ASTEqualsId(int id) {
    super(id);
  }

  public ASTEqualsId(Parser p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    return super.toString() + " [ " + identifier + " ]";
  }

}
/* JavaCC - OriginalChecksum=c03567ff21037260c7db85438c08eec5 (do not edit this line) */
