/* Generated By:JJTree: Do not edit this line. ASTEquals.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEquals extends SimpleNode {
  public ASTEquals(int id) {
    super(id);
  }

  public ASTEquals(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=772ac0513ece9c04f3712e1f270997dc (do not edit this line) */
