/* Generated By:JJTree: Do not edit this line. ASTIF.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF extends SimpleNode {
  public ASTIF(int id) {
    super(id);
  }

  public ASTIF(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c0d5b39185a3cba2ccf6480fcf6cf6a1 (do not edit this line) */
