/* Generated By:JJTree: Do not edit this line. ASTMinus.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMinus extends SimpleNode {
  public ASTMinus(int id) {
    super(id);
  }

  public ASTMinus(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96970fb9d811b154555be6cdf4f3d46d (do not edit this line) */
