/* Generated By:JJTree: Do not edit this line. ASTPlus.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPlus extends SimpleNode {
  public ASTPlus(int id) {
    super(id);
  }

  public ASTPlus(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4dce73bd8dc5dbac2f6dbdcdc4ad5800 (do not edit this line) */
