/* Generated By:JJTree: Do not edit this line. ASTTimes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTimes extends SimpleNode {
  public ASTTimes(int id) {
    super(id);
  }

  public ASTTimes(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0191b6a86f1fdaf000654f1c3ebcdeec (do not edit this line) */
